export const CITY_COLORS: Record<string, string> = {
    'Canada': '#3b82f6',

    'Newfoundland and Labrador': '#ef4444',
    'Prince Edward Island': '#a855f7',
    'Nova Scotia': '#06b6d4',
    'New Brunswick': '#d946ef',
    'Quebec': '#8b5cf6',
    'Ontario': '#10b981',
    'Manitoba': '#f97316',
    'Saskatchewan': '#14b8a6',
    'Alberta': '#ec4899',
    'British Columbia': '#f59e0b',
    'Yukon': '#84cc16',
    'Northwest Territories': '#6366f1',
    'Nunavut': '#22c55e',

    'Toronto, Ontario': '#10b981',
    'Vancouver, British Columbia': '#f59e0b',
    'Montréal, Quebec': '#8b5cf6',
    'Calgary, Alberta': '#ec4899',
    'Edmonton, Alberta': '#14b8a6',
    'Ottawa-Gatineau, Ontario part, Ontario/Quebec': '#6366f1',
    'Winnipeg, Manitoba': '#f97316',
    'Halifax, Nova Scotia': '#06b6d4',
    'St. John\'s, Newfoundland and Labrador': '#84cc16',
    'Charlottetown, Prince Edward Island': '#a855f7',
    'Saint John, Fredericton, and Moncton, New Brunswick': '#d946ef',
    'Quebec, Quebec': '#0ea5e9',
    'Sherbrooke, Quebec': '#f43f5e',
    'Trois-Rivières, Quebec': '#22c55e',
    'Oshawa, Ontario': '#eab308',
    'Hamilton, Ontario': '#ef4444',
    'St. Catharines-Niagara, Ontario': '#8b5cf6',
    'Kitchener-Cambridge-Waterloo, Ontario': '#06b6d4',
    'Guelph, Ontario': '#f59e0b',
    'London, Ontario': '#10b981',
    'Windsor, Ontario': '#6366f1',
    'Greater Sudbury, Ontario': '#ec4899',
    'Regina, Saskatchewan': '#14b8a6',
    'Saskatoon, Saskatchewan': '#f97316',
    'Kelowna, British Columbia': '#a855f7',
    'Victoria, British Columbia': '#84cc16',
};

export const MAJOR_CITIES = [
    'Canada',
    'Toronto, Ontario',
    'Vancouver, British Columbia',
    'Montréal, Quebec',
    'Calgary, Alberta',
    'Edmonton, Alberta',
    'Winnipeg, Manitoba',
    'Halifax, Nova Scotia',
    'Ottawa-Gatineau, Ontario part, Ontario/Quebec',
];

export const PROVINCES = [
    'Canada',
    'Newfoundland and Labrador',
    'Prince Edward Island',
    'Nova Scotia',
    'New Brunswick',
    'British Columbia',
    'Alberta',
    'Saskatchewan',
    'Manitoba',
    'Ontario',
    'Quebec',
    'Nunavut',
    'Northwest Territories',
    'Yukon',

];